### ISSUE TITLE
Get Twilio response? 

### ISSUE THREAD

**Issue by ProgrammerZ** [laravel-notification-channels/twilio#87]
How to get Twilio response after the SMS message have been sent?

**Comment by atymic** [comment]
Use the `NotificationSent` event which contains the response :)

https://laravel.com/docs/5.8/notifications#notification-events

**Comment by ProgrammerZ** [comment]
I have implemented `NotificationSent` but forgot to add `->toArray()` with `$event->response->toArray()` which got me confused as I was receiving `{}`. 
Thank you for fast response!

**Comment by clod986** [comment]
I still have a test account and keep getting `NULL` as the only response... is this normal?
